[package]
name = "bevy_psx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"

[dev-dependencies]
bevy_fly_camera = "0.10.0"

